### ISSUE TITLE
App's websocket not connecting to my openvidu server's websocket

### ISSUE THREAD

**Issue by abhilash-behera** [sergiopaniego/WebRTCapp#3]
My openvidu server is at url https://greenoxeco.in:4443
In the wss url field in the app I try to enter the url wss://greenoxeco.in:4443 but it says cannot establish connection. My openvidu server also uses basic authentication using the openvidu secret key.

**Comment by shashankjamdade** [comment]
Did you solve the problem? if yes then please tell me.

**Comment by abhilash-behera** [comment]
No I am still stuck with it. Please help me. I am on a production level project.

**Comment by randymuhroji** [comment]
+1

**Comment by abhilash-behera** [comment]
solved this issue by replacing the server.key file in the assets folder with my server's ssl certificate.
